// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA0jX1_IOJw16mrACOqEFLj2iJTnUhGNVQ',
    appId: '1:1085692339779:web:61361b5ff1c15d74b1d6f6',
    messagingSenderId: '1085692339779',
    projectId: 'zmlpavan',
    authDomain: 'zmlpavan.firebaseapp.com',
    storageBucket: 'zmlpavan.firebasestorage.app',
    measurementId: 'G-T734JQKHM9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB-VoGtHO2qxSKWG3_Q5lCr1FFMxOr7VK4',
    appId: '1:1085692339779:android:5ddd2af39dd9cbceb1d6f6',
    messagingSenderId: '1085692339779',
    projectId: 'zmlpavan',
    storageBucket: 'zmlpavan.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCIOFXbyFjCapqbMjLr2bBxyntkmavUWXk',
    appId: '1:1085692339779:ios:868e386bc5ae1a61b1d6f6',
    messagingSenderId: '1085692339779',
    projectId: 'zmlpavan',
    storageBucket: 'zmlpavan.firebasestorage.app',
    iosBundleId: 'com.example.zmlMhWvPavanProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCIOFXbyFjCapqbMjLr2bBxyntkmavUWXk',
    appId: '1:1085692339779:ios:868e386bc5ae1a61b1d6f6',
    messagingSenderId: '1085692339779',
    projectId: 'zmlpavan',
    storageBucket: 'zmlpavan.firebasestorage.app',
    iosBundleId: 'com.example.zmlMhWvPavanProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA0jX1_IOJw16mrACOqEFLj2iJTnUhGNVQ',
    appId: '1:1085692339779:web:61361b5ff1c15d74b1d6f6',
    messagingSenderId: '1085692339779',
    projectId: 'zmlpavan',
    authDomain: 'zmlpavan.firebaseapp.com',
    storageBucket: 'zmlpavan.firebasestorage.app',
    measurementId: 'G-T734JQKHM9',
  );

}